### PR TITLE
Include symbols in package

### PR DESCRIPTION
**Pull request by kzu**
Fixes http://work.azdo.io/917288, fixes AB#917288

### CODE REVIEW

**Comment by kzu** [comment]
Heya @jeffkl how quickly can we get an updated nuget package so we can bump the dep and trigger a new build + insertion round?

**Comment by jeffkl** [comment]
Would it be better to push a symbol package or use SourceLink?  I thought it was a bad practice to include PDBs in NUPKGs?

**Comment by kzu** [comment]
Not really. SourceLink is orthogonal to including the PDB. What's sort of considered "bad" practice, AFAIK, is to actually *embed* the PDB in the DLL, since it might be used in a resource-constrained device (i.e. via Xamarin) and cause unnecessary memory consumption. However, this is not the case here.
Also, it's a PPDB, so it's really really tiny compared to what placing a full PDB was, so, it should be fine.

Finally, for the purposes of VS insertion symbol check, the only thing that would make it green is if in the process of publishing this package, you also uploaded to that symbol server, which I think is way overkill.

**Comment by jeffkl** [comment]
I'm not 100% convinced this is correct but I'd rather unblock you.  Is Microsoft shipping this library?

**Comment by jeffkl** [comment]
Package is pushed, awaiting validation: https://www.nuget.org/packages/Microsoft.Dism/2.0.16

**Comment by kzu** [comment]
It seems we're using it as part of our Xamarin Android Device Manager. @garuma would know what for :)

**Comment by kzu** [comment]
Cool, bumped our dep, on track for insertion! Thanks a lot @jeffkl 💯

**Comment by jeffkl** [comment]
No problem, thanks for the contribution

**Pull request merged**
